name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish GridPuzzleSolver -c Release -r win-x64 -o ./build /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=false /p:SelfContained=false /p:UseAppHost=true

    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Zip artifacts
      run: cd build && zip GridPuzzleSolver-${{ env.RELEASE_VERSION }}.zip *.exe

    - name: Create release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "./build/GridPuzzleSolver-${{ env.RELEASE_VERSION }}.zip"
        bodyFile: "README.md"
        name: ${{ env.RELEASE_VERSION }}